# Generated by Django 4.2.7 on 2023-11-15 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('experience', models.TextField()),
                ('photo', models.ImageField(upload_to='author_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassesRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_short_description', models.CharField(max_length=255)),
                ('video_long_description', models.TextField()),
                ('link', models.URLField()),
                ('video_thumbnail', models.ImageField(upload_to='video_thumbnails/')),
                ('video_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('video_discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_video.categories')),
                ('class_rank_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms_video.classesrank')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_video.subjects')),
                ('video_author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_video.authors')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_video.video')),
            ],
            options={
                'unique_together': {('user', 'video')},
            },
        ),
    ]
