# Generated by Django 4.2.7 on 2023-11-15 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_video', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='class_rank_id',
            new_name='class_rank',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video_author_id',
            new_name='video_author',
        ),
    ]
