# Generated by Django 4.2.7 on 2023-12-14 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_video', '0005_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms_video.categories'),
        ),
    ]
